name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: llm-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and Push
      run: |
        # Navigate to backend directory
        cd backend
        
        # Verify Dockerfile exists
        if [ ! -f "Dockerfile" ]; then
          echo "ERROR: Dockerfile not found in backend directory"
          exit 1
        fi

        # Build and submit from the backend directory
        gcloud builds submit \
          --tag gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --project $PROJECT_ID \
          .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated