name: Deploy to Vertex AI
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy Backend
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/llm-backend backend/
          gcloud run deploy llm-backend \
            --image gcr.io/$PROJECT_ID/llm-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated