name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE_NAME: llm-backend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build Docker image
      run: |
        cd backend
        gcloud builds submit \
          --tag=gcr.io/$PROJECT_ID/$SERVICE_NAME \
          .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image=gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform=managed \
          --region=$REGION \
          --port=8080 \
          --timeout=600 \
          --set-env-vars=PORT=8080 \
 